### ISSUE TITLE
What does "total_mass" actually control?

### ISSUE THREAD

**Issue by kb-devacct** [jan-rybizki/Chempy#18]
Hi there, 

I am struggling to understand how the "total_mass" parameter affects the output. 

The default is to set "total_mass=1" and the SFR "S_0=1" with a comment stating it now uses the normalized SFR rather than the absolute value for SFR. But this is only done for the gamma function SFR. I've tested by comparing total_mass=1,100,1000,10000 and the results are all within error of each other. 

Are you able to provide any additional information on what "total_mass" controls or if it's best left as 1 as all the calculations use "normalized" values?

Thanks

**Comment by NathanSandford** [comment]
It's been a little while since I've played around with things, but my understanding is that the total_mass really is just a normalization factor for the SFR as you've stated. In most cases, this has no direct impact on the time evolution of the chemical abundances, which is relatively common for one-zone models. The main exception to this that I can think of is if you've turned on stochastic sampling of the IMF (stochastic_IMF = True). If that's important to your science (e.g., very low-mass galaxies), then you'll want to pick whatever value gives you the appropriate final mass. But otherwise it doesn't matter too much (or at all) and leaving it at 1 for simplicity might be the way to go.

**Comment by kb-devacct** [comment]
@NathanSandford 
I don't believe I need to use stochastic sampling of the IMF so I can leave it as 1 for my work. 
Thanks for the quick reply!

**Comment by jan-rybizki** [comment]
Thanks for the fast support Nathan!
